### ISSUE TITLE
Screen shot is cached

### ISSUE THREAD

**Issue by munkh-erdene** [learncodebygaming/opencv_tutorials#1]
# get an updated image of the game
screenshot = wincap.get_screenshot()

screenshot is cached, every time i attempt to my game is showing first screenshot.

**Comment by learncodebygaming** [comment]
This does happen for some applications. In those cases, it usually works to capture the entire desktop instead. Try using the code from video #5, where if you set the window_name to None the constructor calls win32gui.GetDesktopWindow().  I explain this @2:12 in video #5: https://youtu.be/7k4j-uL8WSQ?t=132
