### ISSUE TITLE
Getting vscode window 

### ISSUE THREAD

**Issue by lechuhuuha** [learncodebygaming/opencv_tutorials#10]
I use the code from vid #5 . But i encounter problem that's when capture albion online client window instead i get the vscode window.Is there something that's i did wrong ? But when i capture any other windows i can get them.It's only wrong with albion online client window

**Comment by moeinrahimi** [comment]
yeah me too. it clearly finds the process but captures vscode in the output

**Comment by lazuee** [comment]
got the same output... how to fix it? :(

**Comment by MadMowgli** [comment]
Hey guys, not sure if this will help - but I had some struggles with mirroring the game client output as well. It wasn't showing me the VSCode window, however I only catched the first frame of Albion. Ben addressed this issue on his next video, I got the timestamp for you: https://youtu.be/7k4j-uL8WSQ?list=PL1m2M8LQlzfKtkKq2lK5xko4X-8EZzFPI&t=135

Maybe this helps, give a thumbs up if it did or comment if it didn't - so others know what's up.

**Comment by lechuhuuha** [comment]
> Hey guys, not sure if this will help - but I had some struggles with mirroring the game client output as well. It wasn't showing me the VSCode window, however I only catched the first frame of Albion. Ben addressed this issue on his next video, I got the timestamp for you: https://youtu.be/7k4j-uL8WSQ?list=PL1m2M8LQlzfKtkKq2lK5xko4X-8EZzFPI&t=135
> 
> Maybe this helps, give a thumbs up if it did or comment if it didn't - so others know what's up.

yes in the video he explain the way he fix its. So i will close this issue.
